#ifndef GUARD_CONSTANTS_LAYOUTS_H
#define GUARD_CONSTANTS_LAYOUTS_H

#define LAYOUT_SECRET_BASE_RED_CAVE1 1
#define LAYOUT_SECRET_BASE_BROWN_CAVE1 2
#define LAYOUT_SECRET_BASE_BLUE_CAVE1 3
#define LAYOUT_SECRET_BASE_YELLOW_CAVE1 4
#define LAYOUT_SECRET_BASE_TREE1 5
#define LAYOUT_SECRET_BASE_SHRUB1 6
#define LAYOUT_SECRET_BASE_RED_CAVE2 7
#define LAYOUT_SECRET_BASE_BROWN_CAVE2 8
#define LAYOUT_SECRET_BASE_BLUE_CAVE2 9
#define LAYOUT_SECRET_BASE_YELLOW_CAVE2 10
#define LAYOUT_SECRET_BASE_TREE2 11
#define LAYOUT_SECRET_BASE_SHRUB2 12
#define LAYOUT_SECRET_BASE_RED_CAVE3 13
#define LAYOUT_SECRET_BASE_BROWN_CAVE3 14
#define LAYOUT_SECRET_BASE_BLUE_CAVE3 15
#define LAYOUT_SECRET_BASE_YELLOW_CAVE3 16
#define LAYOUT_SECRET_BASE_TREE3 17
#define LAYOUT_SECRET_BASE_SHRUB3 18
#define LAYOUT_SECRET_BASE_RED_CAVE4 19
#define LAYOUT_SECRET_BASE_BROWN_CAVE4 20
#define LAYOUT_SECRET_BASE_BLUE_CAVE4 21
#define LAYOUT_SECRET_BASE_YELLOW_CAVE4 22
#define LAYOUT_SECRET_BASE_TREE4 23
#define LAYOUT_SECRET_BASE_SHRUB4 24
#define LAYOUT_SINGLE_BATTLE_COLOSSEUM 25
#define LAYOUT_TRADE_CENTER 26
#define LAYOUT_RECORD_CORNER 27
#define LAYOUT_DOUBLE_BATTLE_COLOSSEUM 28
#define LAYOUT_LINK_CONTEST_ROOM1 29
#define LAYOUT_UNKNOWN_LINK_CONTEST_ROOM_25_29 30
#define LAYOUT_UNKNOWN_LINK_CONTEST_ROOM_25_30 31
#define LAYOUT_UNKNOWN_LINK_CONTEST_ROOM_25_31 32
#define LAYOUT_UNKNOWN_LINK_CONTEST_ROOM_25_32 33
#define LAYOUT_UNKNOWN_LINK_CONTEST_ROOM_25_33 34
#define LAYOUT_UNKNOWN_LINK_CONTEST_ROOM_25_34 35
#define LAYOUT_LINK_CONTEST_ROOM2 36
#define LAYOUT_LINK_CONTEST_ROOM3 37
#define LAYOUT_LINK_CONTEST_ROOM4 38
#define LAYOUT_LINK_CONTEST_ROOM5 39
#define LAYOUT_LINK_CONTEST_ROOM6 40
#define LAYOUT_UNION_ROOM 41
#define LAYOUT_TABULA_RASA 42

#endif // GUARD_CONSTANTS_LAYOUTS_H
